name: pillar_remote_config
description: Remote configuration package for Pillar framework
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  firebase_remote_config: ^4.4.0
  flutter:
    sdk: flutter
  meta: ^1.12.0
  pillar_core:
    path: ../pillar-core

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: false
