name: pillar_core_example
description: Example application demonstrating pillar_core usage
version: 1.0.0
# Example app - not published

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  pillar_core:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
