name: Validate Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    name: Validate Commit Messages

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Conventional Commits
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: '.commitlintrc.json'

  validate-pr-title:
    runs-on: ubuntu-latest
    name: Validate PR Title

    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          scopes: |
            core
            ui
            auth
            network
            di
            firebase
            docs
            config
